/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiectpoo;

import java.awt.Color;
import java.awt.Component;
import static java.awt.Frame.NORMAL;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JCheckBox;
import sun.text.resources.zh.JavaTimeSupplementary_zh_TW;

/**
 *
 * @author ioio
 */
 
public class Interfata_Principala extends javax.swing.JFrame {

    /**
     * Creates new form Interfata_Principala
     */
    public Interfata_Principala() {
        initComponents(); 
        jScrollPane2.setOpaque(false);
       jScrollPane2.getViewport().setOpaque(false);
       btn_filtre_RAM.setVisible(false);
       btn_filtre_SSD.setVisible(false);
       btn_filtre_HDD.setVisible(false);
      try{
       MyClass.funtie();
      }catch(Exception e)
      {
          e.getStackTrace();
      }
  
    }
    ArrayList<ObiectGeneral> arrayListBuffer = new ArrayList<>();
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTIP = new javax.swing.ButtonGroup();
        pnl_bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        btn_pgPR = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        icon_text1 = new javax.swing.JLabel();
        btn_setari = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        icon_text = new javax.swing.JLabel();
        btn_obNou = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        icon_text2 = new javax.swing.JLabel();
        icon_text3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        telefon_text = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email_text = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_info_PR = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btn_AfisareTotala = new com.k33ptoo.components.KButton();
        btn_filtru_AplicareTIP = new com.k33ptoo.components.KButton();
        SSD_ = new javax.swing.JCheckBox();
        RAM_ = new javax.swing.JCheckBox();
        HDD_ = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        btn_filtre_RAM = new com.k33ptoo.components.KButton();
        btn_filtre_SSD = new com.k33ptoo.components.KButton();
        btn_filtre_HDD = new com.k33ptoo.components.KButton();
        panel_info_Setari = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_info_Obj = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_logout = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_bg.setBackground(new java.awt.Color(255, 255, 255));

        sidebar.setBackground(new java.awt.Color(41, 168, 73));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pgPR.setBackground(new java.awt.Color(119, 220, 132));
        btn_pgPR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pgPRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pgPRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pgPRMouseExited(evt);
            }
        });

        icon1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        icon1.setForeground(new java.awt.Color(255, 255, 255));
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/icons8-house-30.png"))); // NOI18N

        icon_text1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        icon_text1.setForeground(new java.awt.Color(255, 255, 255));
        icon_text1.setText("Pagina Principala");

        javax.swing.GroupLayout btn_pgPRLayout = new javax.swing.GroupLayout(btn_pgPR);
        btn_pgPR.setLayout(btn_pgPRLayout);
        btn_pgPRLayout.setHorizontalGroup(
            btn_pgPRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pgPRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_text1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );
        btn_pgPRLayout.setVerticalGroup(
            btn_pgPRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_pgPRLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_pgPRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(icon_text1)
                    .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidebar.add(btn_pgPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 50));

        btn_setari.setBackground(new java.awt.Color(107, 198, 110));
        btn_setari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_setariMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_setariMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_setariMouseExited(evt);
            }
        });

        icon.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 255));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/icons8-settings-30.png"))); // NOI18N

        icon_text.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        icon_text.setForeground(new java.awt.Color(255, 255, 255));
        icon_text.setText("Setari");

        javax.swing.GroupLayout btn_setariLayout = new javax.swing.GroupLayout(btn_setari);
        btn_setari.setLayout(btn_setariLayout);
        btn_setariLayout.setHorizontalGroup(
            btn_setariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_setariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_text, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_setariLayout.setVerticalGroup(
            btn_setariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_setariLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_setariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(icon_text)
                    .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidebar.add(btn_setari, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 50));

        btn_obNou.setBackground(new java.awt.Color(107, 198, 110));
        btn_obNou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_obNouMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_obNouMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_obNouMouseExited(evt);
            }
        });

        icon2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        icon2.setForeground(new java.awt.Color(255, 255, 255));
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/icons8-add-30.png"))); // NOI18N

        icon_text2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        icon_text2.setForeground(new java.awt.Color(255, 255, 255));
        icon_text2.setText("Obiect nou");

        javax.swing.GroupLayout btn_obNouLayout = new javax.swing.GroupLayout(btn_obNou);
        btn_obNou.setLayout(btn_obNouLayout);
        btn_obNouLayout.setHorizontalGroup(
            btn_obNouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_obNouLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_text2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );
        btn_obNouLayout.setVerticalGroup(
            btn_obNouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_obNouLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_obNouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btn_obNouLayout.createSequentialGroup()
                        .addComponent(icon_text2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        sidebar.add(btn_obNou, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 50));

        icon_text3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        icon_text3.setForeground(new java.awt.Color(255, 255, 255));
        icon_text3.setText("COMBO");
        sidebar.add(icon_text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        sidebar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 20));

        jPanel2.setBackground(new java.awt.Color(119, 197, 220));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Magazinul nr.1 in Romania ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pentru orice problema tehnica sunati la numarul:");

        telefon_text.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        telefon_text.setForeground(new java.awt.Color(255, 255, 255));
        telefon_text.setText("+40 07******* ");
        telefon_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telefon_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                telefon_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                telefon_textMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("sau email la adresa:");

        email_text.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        email_text.setForeground(new java.awt.Color(255, 255, 255));
        email_text.setText("tehnic@combo.com");
        email_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        email_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                email_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                email_textMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefon_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_text))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(telefon_text)
                    .addComponent(jLabel5)
                    .addComponent(email_text))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        panel_info_PR.setkEndColor(new java.awt.Color(119, 197, 220));
        panel_info_PR.setkStartColor(new java.awt.Color(41, 168, 73));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Aici o sa se afiseze produsele selectate");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setBackground(new java.awt.Color(107, 198, 110));
        jScrollPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(119, 197, 220));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_AfisareTotala.setText("AFISARE TOTALA");
        btn_AfisareTotala.setkHoverColor(new java.awt.Color(119, 197, 220));
        btn_AfisareTotala.setkHoverEndColor(new java.awt.Color(119, 197, 220));
        btn_AfisareTotala.setkHoverForeGround(new java.awt.Color(188, 217, 231));
        btn_AfisareTotala.setkHoverStartColor(new java.awt.Color(41, 168, 73));
        btn_AfisareTotala.setkPressedColor(new java.awt.Color(220, 119, 156));
        btn_AfisareTotala.setkStartColor(new java.awt.Color(119, 197, 220));
        btn_AfisareTotala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AfisareTotalaMouseClicked(evt);
            }
        });
        btn_AfisareTotala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AfisareTotalaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_AfisareTotala, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 27));

        btn_filtru_AplicareTIP.setText(" Aplicare Tip Produs");
        btn_filtru_AplicareTIP.setkHoverColor(new java.awt.Color(119, 197, 220));
        btn_filtru_AplicareTIP.setkHoverEndColor(new java.awt.Color(119, 197, 220));
        btn_filtru_AplicareTIP.setkHoverForeGround(new java.awt.Color(188, 217, 231));
        btn_filtru_AplicareTIP.setkHoverStartColor(new java.awt.Color(41, 168, 73));
        btn_filtru_AplicareTIP.setkPressedColor(new java.awt.Color(220, 119, 156));
        btn_filtru_AplicareTIP.setkStartColor(new java.awt.Color(119, 197, 220));
        btn_filtru_AplicareTIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_filtru_AplicareTIPMouseClicked(evt);
            }
        });
        btn_filtru_AplicareTIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtru_AplicareTIPActionPerformed(evt);
            }
        });
        jPanel1.add(btn_filtru_AplicareTIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        buttonGroupTIP.add(SSD_);
        SSD_.setText("SSD");
        SSD_.setOpaque(false);
        jPanel1.add(SSD_, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        buttonGroupTIP.add(RAM_);
        RAM_.setText("RAM");
        RAM_.setOpaque(false);
        RAM_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RAM_MouseClicked(evt);
            }
        });
        jPanel1.add(RAM_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        buttonGroupTIP.add(HDD_);
        HDD_.setText("HDD");
        HDD_.setOpaque(false);
        jPanel1.add(HDD_, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jCheckBox1.setText("Pret RAM <300");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jCheckBox2.setText("Comunicare Simpla");
        jCheckBox2.setOpaque(false);
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jCheckBox3.setText("Pret HDD >2000");
        jCheckBox3.setActionCommand("");
        jCheckBox3.setOpaque(false);
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, -1));

        btn_filtre_RAM.setText("Filtre Ram");
        btn_filtre_RAM.setkHoverColor(new java.awt.Color(119, 197, 220));
        btn_filtre_RAM.setkHoverEndColor(new java.awt.Color(119, 197, 220));
        btn_filtre_RAM.setkHoverForeGround(new java.awt.Color(188, 217, 231));
        btn_filtre_RAM.setkHoverStartColor(new java.awt.Color(41, 168, 73));
        btn_filtre_RAM.setkPressedColor(new java.awt.Color(220, 119, 156));
        btn_filtre_RAM.setkStartColor(new java.awt.Color(119, 197, 220));
        btn_filtre_RAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_filtre_RAMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_filtre_RAMMouseEntered(evt);
            }
        });
        btn_filtre_RAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtre_RAMActionPerformed(evt);
            }
        });
        jPanel1.add(btn_filtre_RAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        btn_filtre_SSD.setText("Filtre SSD");
        btn_filtre_SSD.setkHoverColor(new java.awt.Color(119, 197, 220));
        btn_filtre_SSD.setkHoverEndColor(new java.awt.Color(119, 197, 220));
        btn_filtre_SSD.setkHoverForeGround(new java.awt.Color(188, 217, 231));
        btn_filtre_SSD.setkHoverStartColor(new java.awt.Color(41, 168, 73));
        btn_filtre_SSD.setkPressedColor(new java.awt.Color(220, 119, 156));
        btn_filtre_SSD.setkStartColor(new java.awt.Color(119, 197, 220));
        btn_filtre_SSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtre_SSDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_filtre_SSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        btn_filtre_HDD.setText("Filtre HDD");
        btn_filtre_HDD.setkHoverColor(new java.awt.Color(119, 197, 220));
        btn_filtre_HDD.setkHoverEndColor(new java.awt.Color(119, 197, 220));
        btn_filtre_HDD.setkHoverForeGround(new java.awt.Color(188, 217, 231));
        btn_filtre_HDD.setkHoverStartColor(new java.awt.Color(41, 168, 73));
        btn_filtre_HDD.setkPressedColor(new java.awt.Color(220, 119, 156));
        btn_filtre_HDD.setkStartColor(new java.awt.Color(119, 197, 220));
        btn_filtre_HDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_filtre_HDDMouseClicked(evt);
            }
        });
        btn_filtre_HDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtre_HDDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_filtre_HDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout panel_info_PRLayout = new javax.swing.GroupLayout(panel_info_PR);
        panel_info_PR.setLayout(panel_info_PRLayout);
        panel_info_PRLayout.setHorizontalGroup(
            panel_info_PRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_PRLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_info_PRLayout.setVerticalGroup(
            panel_info_PRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
            .addGroup(panel_info_PRLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_info_PR, "card2");

        panel_info_Setari.setkEndColor(new java.awt.Color(119, 197, 220));
        panel_info_Setari.setkStartColor(new java.awt.Color(41, 168, 73));

        jLabel4.setText("Panel info Pagina cu setari");

        javax.swing.GroupLayout panel_info_SetariLayout = new javax.swing.GroupLayout(panel_info_Setari);
        panel_info_Setari.setLayout(panel_info_SetariLayout);
        panel_info_SetariLayout.setHorizontalGroup(
            panel_info_SetariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_SetariLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 793, Short.MAX_VALUE))
        );
        panel_info_SetariLayout.setVerticalGroup(
            panel_info_SetariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_SetariLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 360, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_info_Setari, "card3");

        panel_info_Obj.setkEndColor(new java.awt.Color(119, 197, 220));
        panel_info_Obj.setkStartColor(new java.awt.Color(41, 168, 73));

        jLabel6.setText("Panel info Pagina cu obiecte noi");

        javax.swing.GroupLayout panel_info_ObjLayout = new javax.swing.GroupLayout(panel_info_Obj);
        panel_info_Obj.setLayout(panel_info_ObjLayout);
        panel_info_ObjLayout.setHorizontalGroup(
            panel_info_ObjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_ObjLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 752, Short.MAX_VALUE))
        );
        panel_info_ObjLayout.setVerticalGroup(
            panel_info_ObjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_info_ObjLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 360, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panel_info_Obj, "card4");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("WE");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/icons8-heart-24.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("COMBO");

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setBorder(null);
        btn_logout.setText("Logout");
        btn_logout.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        btn_logout.setkBackGroundColor(new java.awt.Color(153, 0, 153));
        btn_logout.setkBorderRadius(-20);
        btn_logout.setkHoverColor(new java.awt.Color(119, 197, 220));
        btn_logout.setkHoverEndColor(new java.awt.Color(119, 197, 220));
        btn_logout.setkHoverForeGround(new java.awt.Color(188, 217, 231));
        btn_logout.setkHoverStartColor(new java.awt.Color(41, 168, 73));
        btn_logout.setkPressedColor(new java.awt.Color(220, 119, 156));
        btn_logout.setkStartColor(new java.awt.Color(119, 197, 220));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_bgLayout = new javax.swing.GroupLayout(pnl_bg);
        pnl_bg.setLayout(pnl_bgLayout);
        pnl_bgLayout.setHorizontalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1)
                    .addGroup(pnl_bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnl_bgLayout.setVerticalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefon_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefon_textMouseEntered
        // TODO add your handling code here:
        telefon_text.setForeground(new Color(119,220,132));
    }//GEN-LAST:event_telefon_textMouseEntered

    private void telefon_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefon_textMouseExited
        // TODO add your handling code here:
        telefon_text.setForeground(Color.WHITE);
    }//GEN-LAST:event_telefon_textMouseExited

    private void email_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_textMouseEntered
        // TODO add your handling code here:
        email_text.setForeground(new Color(119,220,132));
    }//GEN-LAST:event_email_textMouseEntered

    private void email_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_textMouseExited
        // TODO add your handling code here:
        email_text.setForeground(Color.WHITE);
    }//GEN-LAST:event_email_textMouseExited

    private void btn_pgPRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pgPRMouseClicked
        // TODO add your handling code here:
        panel_info_PR.setVisible(true);
        panel_info_Setari.setVisible(false);
        panel_info_Obj.setVisible(false);
        btn_pgPR.setBackground(new Color(220, 119, 156));
        
    }//GEN-LAST:event_btn_pgPRMouseClicked

    private void btn_setariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setariMouseClicked
        // TODO add your handling code here:
        panel_info_PR.setVisible(false);
        panel_info_Setari.setVisible(true);
        panel_info_Obj.setVisible(false);
        btn_setari.setBackground(new Color(220, 119, 156));
    }//GEN-LAST:event_btn_setariMouseClicked

    private void btn_obNouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_obNouMouseClicked
        // TODO add your handling code here:
        panel_info_PR.setVisible(false);
        panel_info_Setari.setVisible(false);
        panel_info_Obj.setVisible(true);
        btn_obNou.setBackground(new Color(220, 119, 156));
    }//GEN-LAST:event_btn_obNouMouseClicked

    private void btn_pgPRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pgPRMouseEntered
        // TODO add your handling code here:
        btn_pgPR.setBackground(new Color(119,197,220));
    }//GEN-LAST:event_btn_pgPRMouseEntered

    private void btn_pgPRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pgPRMouseExited
        // TODO add your handling code here:
        btn_pgPR.setBackground(new Color(119,220,132));
    }//GEN-LAST:event_btn_pgPRMouseExited

    private void btn_setariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setariMouseEntered
        // TODO add your handling code here:
        btn_setari.setBackground(new Color(119,197,220));
    }//GEN-LAST:event_btn_setariMouseEntered

    private void btn_setariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_setariMouseExited
        // TODO add your handling code here:
        btn_setari.setBackground(new Color(107,198,110));
    }//GEN-LAST:event_btn_setariMouseExited

    private void btn_obNouMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_obNouMouseEntered
        // TODO add your handling code here:
        btn_obNou.setBackground(new Color(119,197,220));
    }//GEN-LAST:event_btn_obNouMouseEntered

    private void btn_obNouMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_obNouMouseExited
        // TODO add your handling code here:
        btn_obNou.setBackground(new Color(107,198,110));
    }//GEN-LAST:event_btn_obNouMouseExited

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
                Interfata_Logare in=new Interfata_Logare();
                in.show();
                dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_AfisareTotalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AfisareTotalaMouseClicked
        // TODO add your handling code here:
          ArrayList<ObiectGeneral> arrayList = new ArrayList<>();

    try  {
        ObjectInputStream objectInputStream =
                new ObjectInputStream(new FileInputStream("data.olivera"));
        while (true) {
            Object read = objectInputStream.readObject();
            if (read == null)
                break;

            // We should always cast explicitly
            ObiectGeneral myClassRead = (ObiectGeneral) read;
            arrayList.add(myClassRead);
        }
    }
    catch (EOFException e) {
        // This exception is expected
    }   catch (IOException ex) {
            Logger.getLogger(Interfata_Principala.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Interfata_Principala.class.getName()).log(Level.SEVERE, null, ex);
        }
    jTextArea1.setText("");
    for (ObiectGeneral m : arrayList) {
        
        jTextArea1.append(m.toString()+"\n");
       
    }
    }//GEN-LAST:event_btn_AfisareTotalaMouseClicked

    private void btn_AfisareTotalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AfisareTotalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AfisareTotalaActionPerformed

    private void btn_filtru_AplicareTIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtru_AplicareTIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_filtru_AplicareTIPActionPerformed

    
    
     
    
    private void btn_filtru_AplicareTIPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filtru_AplicareTIPMouseClicked
        // TODO add your handling code here:
        ///--------------------aici citesc datele din buffer dupa ce au fost modificate si le afisez--------------------  
         ArrayList<ObiectGeneral> arrayList = new ArrayList<>();
         
          try  {
              ObjectInputStream objectInputStream =
                new ObjectInputStream(new FileInputStream("data.olivera"));

        while (true) {
            
            Object read = objectInputStream.readObject();
            if (read == null)
                break;

            
            // We should always cast explicitly
            ObiectGeneral myClassRead = (ObiectGeneral) read;
            arrayList.add(myClassRead);
        }
    }
    catch (Exception e) {
        // This exception is expected
    }
  
    arrayListBuffer.clear();
    
         Component[] comp = jPanel1.getComponents();
          int tip_scriere=0;
        for (int i = 0;i<comp.length;i++) {
        if (comp[i] instanceof JCheckBox) {

            JCheckBox nBox=(JCheckBox)comp[i];
           
            if(nBox.isSelected()==true)
            {
               String name=nBox.getText();
               if(name.equals("RAM"))
               {jTextArea1.setText("");
                         btn_filtre_RAM.setVisible(true);
                         btn_filtre_SSD.setVisible(false);
                         btn_filtre_HDD.setVisible(false);
                   for (ObiectGeneral m : arrayList) 
                   {
                       {
                           if(m.getClass().getCanonicalName().contains("RAM")==true)
                           {    jTextArea1.append("RAM"+"\n");
                               jTextArea1.append(m.toString()+"\n");
                               arrayListBuffer.add(m);
                           }
                       }
                  }
               }
               if(name.equals("HDD"))
               {
                         jTextArea1.setText("");
                         btn_filtre_RAM.setVisible(false);
                         btn_filtre_SSD.setVisible(false);
                         btn_filtre_HDD.setVisible(true);
                       
                             
                   for (ObiectGeneral m : arrayList) 
                   {            
                       {
                           if(m.getClass().getCanonicalName().contains("HDD")==true)
                           {   jTextArea1.append("HDD"+"\n");
                               jTextArea1.append(m.toString()+"\n");
                               arrayListBuffer.add(m);
                           }
                       }
                  }
                         
                  
               }
                if(name.equals("SSD"))
               {jTextArea1.setText("");
                         btn_filtre_RAM.setVisible(false);
                         btn_filtre_SSD.setVisible(true);
                         btn_filtre_HDD.setVisible(false);
                   for (ObiectGeneral m : arrayList) 
                   {
                       {
                           if(m.getClass().getCanonicalName().contains("SSD")==true)
                           {jTextArea1.append("SSD"+"\n");
                               jTextArea1.append(m.toString()+"\n");
                               arrayListBuffer.add(m);
                           }
                       }
                  }
               }
            }
           
    }
   }      
//    try  {
//        //deschid fisierul in care am scris datele
//        ObjectInputStream objectInputStream =
//                new ObjectInputStream(new FileInputStream("buffer.olivera"));
//        //resetez zona de text
//        jTextArea1.setText("");
//        while (true) {
//            //citesc obiecte
//            Object read = objectInputStream.readObject();
//            if (read == null)
//                break;
//            // We should always cast explicitly+afisare
//            ObiectGeneral myClassRead = (ObiectGeneral) read;
//            jTextArea1.append(myClassRead.toString()+"\n"); 
//        }
//        
//    }
//    catch (EOFException e) {
//        // This exception is expected
//    }   catch (IOException ex) {
//            Logger.getLogger(Interfata_Principala.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Interfata_Principala.class.getName()).log(Level.SEVERE, null, ex);
//    }
//   ///--------------------aici reincarc datele din fisierul_mama in buffer pentru a putea fi filtrat again--------------------   
//    try  {
//        //deschid fisierul_mama din care citesc
//        ObjectInputStream objectInputStream =
//                new ObjectInputStream(new FileInputStream("data.olivera"));
//        //deschid fisierul_buffer din care scriu
//        ObjectOutputStream os3 = new ObjectOutputStream(new FileOutputStream("buffer.olivera")) ;
//        while (true) {
//            Object read = objectInputStream.readObject();
//            if (read == null)
//                break;
//
//            // We should always cast explicitly+scriere in buffer
//            ObiectGeneral myClassRead = (ObiectGeneral) read;
//            os3.writeObject(myClassRead);
//        }
//    }
//    catch (EOFException e) {
//        // This exception is expected
//    }   catch (FileNotFoundException ex) {
//            Logger.getLogger(Interfata_Principala.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(Interfata_Principala.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Interfata_Principala.class.getName()).log(Level.SEVERE, null, ex);
//        }
    
    }//GEN-LAST:event_btn_filtru_AplicareTIPMouseClicked

    private void RAM_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RAM_MouseClicked
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_RAM_MouseClicked

    private void btn_filtre_RAMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filtre_RAMMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_filtre_RAMMouseEntered

    private void btn_filtre_RAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtre_RAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_filtre_RAMActionPerformed

    private void btn_filtre_SSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtre_SSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_filtre_SSDActionPerformed

    private void btn_filtre_RAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filtre_RAMMouseClicked
        // TODO add your handling code here:
        
        ArrayList<RAM> obj_curent=new ArrayList<>();
        obj_curent=(ArrayList<RAM>)arrayListBuffer.clone();
        Component[] comp = jPanel1.getComponents();
        for (int i = 0;i<comp.length;i++) {
        if (comp[i] instanceof JCheckBox) {

            JCheckBox nBox=(JCheckBox)comp[i];
           
            if(nBox.isSelected()==true)
            {
               String name=nBox.getText();
               if(name.equals("Pret RAM <300"))
               {
                   for (ObiectGeneral m : arrayListBuffer) 
                   {
                       {
                           if(m.getClass().getCanonicalName().contains("RAM")==true)
                           {    
                               RAM ram=RAM.class.cast(m);
                              if(!(ram.getPret()<300f))
                              {
                                  obj_curent.remove(ram);
                              }
                           
                           }
                       }
                  }
               }
               if(name.equals("Comunicare Simpla"))
               {
                   for (ObiectGeneral m : arrayListBuffer) 
                   {
                       {
                           if(m.getClass().getCanonicalName().contains("RAM")==true)
                           {    
                               RAM ram=RAM.class.cast(m);
                              if(!(ram.getTipComunicare().equals("Single channel")))
                              {
                                  obj_curent.remove(ram);
                              }
                           
                           }
                       }
                  }
               }
             
              
            }
           
    } 
        
   } 
        if(obj_curent.isEmpty()==false)
        {jTextArea1.setText("");
        for(RAM r:obj_curent)
        {
            jTextArea1.append(r.toString()+"\n");
        }}
        else{jTextArea1.setText("Nu exista produse cu aceste caracteristici");}
        
       
    }//GEN-LAST:event_btn_filtre_RAMMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_filtre_HDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtre_HDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_filtre_HDDActionPerformed

    private void btn_filtre_HDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filtre_HDDMouseClicked
        // TODO add your handling code here:
         
         ArrayList<HDD> obj_curent=new ArrayList<>();
        obj_curent=(ArrayList<HDD>)arrayListBuffer.clone();
        Component[] comp = jPanel1.getComponents();
        for (int i = 0;i<comp.length;i++) {
        if (comp[i] instanceof JCheckBox) {

            JCheckBox nBox=(JCheckBox)comp[i];
           
            if(nBox.isSelected()==true)
            {
               String name=nBox.getText();
               if(name.equals("Pret HDD >2000"))
               {
                   for (ObiectGeneral m : arrayListBuffer) 
                   {
                       {
                           if(m.getClass().getCanonicalName().contains("HDD")==true)
                           {    
                               HDD hdd=HDD.class.cast(m);
                              if(!(hdd.getPret()>2000f))
                              {
                                  obj_curent.remove(hdd);
                              }
                           
                           }
                       }
                  }
               }
               
               
             
              
            }
           
    } 
        
   } 
        if(obj_curent.isEmpty()==false)
        {jTextArea1.setText("");
        for(HDD r:obj_curent)
        {
            jTextArea1.append(r.toString()+"\n");
        }}
        else{jTextArea1.setText("Nu exista produse cu aceste caracteristici");}
        
    }//GEN-LAST:event_btn_filtre_HDDMouseClicked
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfata_Principala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfata_Principala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfata_Principala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfata_Principala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfata_Principala().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox HDD_;
    private javax.swing.JCheckBox RAM_;
    private javax.swing.JCheckBox SSD_;
    private com.k33ptoo.components.KButton btn_AfisareTotala;
    private com.k33ptoo.components.KButton btn_filtre_HDD;
    private com.k33ptoo.components.KButton btn_filtre_RAM;
    private com.k33ptoo.components.KButton btn_filtre_SSD;
    private com.k33ptoo.components.KButton btn_filtru_AplicareTIP;
    private com.k33ptoo.components.KButton btn_logout;
    private javax.swing.JPanel btn_obNou;
    private javax.swing.JPanel btn_pgPR;
    private javax.swing.JPanel btn_setari;
    private javax.swing.ButtonGroup buttonGroupTIP;
    private javax.swing.JLabel email_text;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon_text;
    private javax.swing.JLabel icon_text1;
    private javax.swing.JLabel icon_text2;
    private javax.swing.JLabel icon_text3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private keeptoo.KGradientPanel panel_info_Obj;
    private keeptoo.KGradientPanel panel_info_PR;
    private keeptoo.KGradientPanel panel_info_Setari;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel telefon_text;
    // End of variables declaration//GEN-END:variables

    void setExtendedState() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
